spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:H2
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org.hibernate.type: trace